# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ publish ]
  pull_request:
    branches: [ publish ]

jobs:
  build:

    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        # cache: 'npm'
    - run: npm install yarn -g
    - run: yarn install
    - run: npm run dist:ci

        # 下面主要是创建 github 的release
    # 使用 tyankatsu0105/read-package-version-actions@v1 工具来读取对应的package.json 数据
    - name: Read package.json
      uses: tyankatsu0105/read-package-version-actions@v1
      with:
        path: '.'
      id: package-version

      # 关于创建 release 的更多参数，可以查看 actions/create-release@v1
    - name: Create Release for Tag
      id: release_tag
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: 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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 # 这块需要用到 github的token，因为需要对分之进行代码推送
      with:
        tag_name: frontEnd${{ steps.package-version.outputs.version }}
        release_name: Release frontEndfrontEnd${{ steps.package-version.outputs.version }}
        prerelease: false # 是否为预发布版本
